### ISSUE TITLE
Clicking search without selecting a new location doesn't work

### ISSUE THREAD

**Issue by mbatilando** [jamietsao/codepath-mapstagram#130]

**Comment by mbatilando** [comment]
@jamietsao @kristen This bug is basically because chosenLocation is not set since the user hasn't chosen a location when they open the search view. SessionService has the previous CLLocation stored in searchLocation, but doesn't have the name to display in the search bar. Was wondering if the best way to fix this bug is to change searchLocation to be a Location object instead of just a CLLocation.

**Comment by jamietsao** [comment]
SessionService has the name in the `searchLocationName` field, but it probably makes sense to replace 'searchLocation' and 'searchLocationName' with a Location object like you suggested.  But I think the real issue is that `chosenLocation` isn't initialized in `SearchViewController.viewDidLoad()`.  Changing to use Location object will make the initialization easier.

**Comment by mbatilando** [comment]
#133
