### ISSUE TITLE
I've been noticing duplicate photos (sometimes up to three) in infinite scroll

### ISSUE THREAD

**Issue by kristen** [jamietsao/codepath-mapstagram#151]

**Comment by kristen** [comment]
![image](https://cloud.githubusercontent.com/assets/1939235/6805879/b5e9e650-d202-11e4-95d1-13fecb962db8.jpg)

**Comment by jamietsao** [comment]
Yeah, @mbatilando noticed the same yesterday.  Probably the dreaded off by 1 error.

**Comment by mbatilando** [comment]
That's weird. Is it copying the more than one photo? The way I'm doing it now is I'm removing the first element in the array from the API call because it's the same as the last photo in the media array. Then I combine the two. I'm actually also getting this duplicate (although only one photo) when I'm doing pull-to-refresh on my branch when I'm in my current location. But switching to another location fixes it...

Any quick fixes you guys think we should do? I mean we can go through the array and remove duplicate media with more than one place ids. Not sure if that's the most efficient though..

**Comment by kristen** [comment]
Maybe more than one photo has the same timestamp...

**Comment by mbatilando** [comment]
Yeah I think that's the case

**Comment by kristen** [comment]
Maybe instead of assuming it's only the first element in the array, we should check if the timestamp is the same and exclude based on that.

**Comment by jamietsao** [comment]
I would first debug to see if this is a bug on our end that can be fixed, but if Instagram does indeed return dup photos, then we might have to keep a hash of media IDs, then loop through the array returned from each API call, and remove dups unfortunately.  Hopefully it's not too expensive performance wise.

**Comment by mbatilando** [comment]
So I looked into it and I believe it's because multiple photos in the media array can have the exact same timestamp (similar to what @kristen said). Because of that, we get multiple duplicates (not just the latest photo) if we query using minTimestamp. I don't see an easy way of knowing how much to slice the array after getting the response from the API call. It may be best to use a hash and check each new Media element id if it's in the hash already just like what @jamietsao said. What do you guys think?

**Comment by kristen** [comment]
@mbatilando you did mention maybe changing the timestamp by the smallest amount and not removing items from the array. Do you think that is possible?

**Comment by mbatilando** [comment]
I think that's possible, but it might still exclude photos with the same timestamp that hasn't propagated to the API yet.

**Comment by mbatilando** [comment]
#153
