### ISSUE TITLE
Polish: Slider for all views w/ Infinite Scroll

### ISSUE THREAD

**Issue by mbatilando** [jamietsao/codepath-mapstagram#94]

**Comment by mbatilando** [comment]
Is this basically #131?

**Comment by kristen** [comment]
Honestly, I have no idea what this is for... Didn't you create this, lol?

**Comment by jamietsao** [comment]
Yeah, I looking at this issue today and forgot what this was exactly, but I think you're right.  We wanted to add a refresh control to the bottom (of grid/list) and the right of map.  But at this point, this might be a bonus item, unless you think it's do-able.  Not sure how difficult it is.

In any event, I think you can close this issue since it's a dup of 131.

**Comment by mbatilando** [comment]
Haha yeah I called it a slider instead of refresh control. Not sure how easy this actually is. I quickly tried it in the list view and couldn't get it to work. We can take a look at it more tonight if we want.
